server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
- url: http://loki:3100/loki/api/v1/push

scrape_configs:
# Configuration pour l'application Node.js Express
- job_name: node_app_logs
  static_configs:
  - targets:
    - localhost
    labels:
      job: node-app
      service: node-app
      __path__: /node-app/logs/node-app.log
  pipeline_stages:
  - json:
      expressions:
        level: level
        msg: message
        time: timestamp
        service: service
  - labels:
      level:
      service:
  - timestamp:
      source: time
      format: RFC3339

# Configuration pour l'application NestJS
- job_name: nest_app_logs
  static_configs:
  - targets:
    - localhost
    labels:
      job: nest-app
      service: nest-app
      __path__: /nest-app/logs/nest-app.log
  pipeline_stages:
  - json:
      expressions:
        level: level
        msg: message
        time: timestamp
        service: service
  - labels:
      level:
      service:
  - timestamp:
      source: time
      format: RFC3339

# Configuration pour l'application Next.js
- job_name: next_app_logs
  static_configs:
  - targets:
    - localhost
    labels:
      job: next-app
      service: next-app
      __path__: /next-app/logs/next-app.log
  pipeline_stages:
  - json:
      expressions:
        level: level
        msg: message
        time: timestamp
        service: service
  - labels:
      level:
      service:
  - timestamp:
      source: time
      format: RFC3339

# Configuration générique pour tous les logs du dossier (optionnel)
- job_name: all_app_logs
  static_configs:
  - targets:
    - localhost
    labels:
      job: app-logs
      __path__: /logs/*.log
  pipeline_stages:
  - json:
      expressions:
        level: level
        msg: message
        time: timestamp
        service: service
  - labels:
      level:
      service:
  - timestamp:
      source: time
      format: RFC3339