apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  version: 1
  editable: true
  uid: prometheus
  isDefault: false
  jsonData:
    httpMethod: POST
    queryTimeout: 60s
    timeInterval: 15s

- name: Tempo
  type: tempo
  access: proxy
  url: http://tempo:3200
  isDefault: true
  version: 1
  editable: true
  uid: tempo
  jsonData:
    nodeGraph:
      enabled: true
    tracesToLogs:
      datasourceUid: loki
      spanStartTimeShift: "-1h"
      spanEndTimeShift: "1h"
      tags: [ { key: 'trace_id', value: 'trace_id' } ]
      filterByTraceID: true

- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  version: 1
  editable: true
  uid: loki
  jsonData:
    derivedFields:
    - datasourceUid: tempo
      matcherRegex: "trace_id=(\\w+)"
      name: TraceID
      url: "$${__value.raw}"
